### ISSUE TITLE
Controller creation

### ISSUE THREAD

**Issue by Pavani-Vithala** [daibhidhdwaum/healthywolves#8]
The purpose of this view to to create the required routes and the server.js

**Comment by SarynSummer** [comment]
Tentative Routing Plan

# HTML Routes

--- router.get("/") 

-Display homepage
-User Login Form
-Calls default graph(s)? (could show site wide average data on landing page in pane where user input will go once they log in)

--- router.get("/user/acct")

display receipt history of specified user
display new receipt input form
display graphs/graph options

# API Routes

- app.get("api/all") (calls all user data from receipts table)

- app.get("api/user/:ID") (user validation (aka login))

- app.get("api/receipts?user_ID=xxxx") (grabs all receipts for a specific user) [express route filter param google]

- app.get("api/items?receipt_ID=xxxx") (grabs all items for a specific receipt) [express route filter param google]

- app.post("api/user") (creates new user)

- app.post("api/receipt") (creates new receipt for a user)

- app.post("api/item") (creates items as separate lines on a master items table tagged with user_ID and receipt_ID)

- app.delete("api/user") (delete user)

- app.delete("api/receipt") (delete receipt record INCLUDING all connected items)

**Comment by SarynSummer** [comment]
Good progress on this, not finished by any stretch but it's looking good. Done for the day now most likely.

**Comment by SarynSummer** [comment]
api routing is nearly complete for users, item routing is started but need lots of work

**Comment by SarynSummer** [comment]
HTML routing for both pages complete will create new issue for remaining api routes
